org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.233
loader_version_range=[4,)

mod_version=1.6.0
mod_id=mining_dims
mod_name=Mining Dimensions
mod_license=MIT
mod_group_id=com.kwpugh.mining_dims
